version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./processed_files:/app/processed_files  # Persist processed files
    environment:
      - PYTHONPATH=/app